#!/bin/sh

function installKernel() {
	dialog --title "Installing Kernel" --infobox "Installing linux-tkg kernel" 0 0 && sleep 1
	cd ~/Documents/git/
	git clone https://github.com/Frogging-Family/linux-tkg.git
	cd linux-tkg/
	./install.sh install
}

installKernel
