#!/bin/sh

# Get CPU count
threadCount="$(grep processor /proc/cpuinfo | wc -l)"

# Counter for creating variables to store all CPU's frequencies
counter=1

# Get frequencies of all found threads for notification
notification="$(for (( core = 1; core <= $threadCount; core++ )); do eval "echo "Core $counter: "$(grep MHz /proc/cpuinfo | awk -v var=$core 'NR == var {printf "%.2f", $4/1000}')"" GHz"; counter=$((counter+1)); done)"

# Icon to display
icon=

# Define mouse controls
case $BUTTON in
	# Left-click opens up a terminal showing frequency of all threads
	1) setsid -f "$TERMINAL" -e watch grep MHz /proc/cpuinfo ;;
	# Right-click shows a notification with all the found CPU's frequencies
	3) notify-send "Frequency" "$notification"
esac

# Get frequency of first core
frequency="$(grep MHz /proc/cpuinfo | awk 'NR == 1 {printf "%.2f", $4/1000}')"

# Display CPU icon and frequency of first core
echo "$icon $frequency GHz"
