#!/bin/sh

# Get CPU usage
usage="$(mpstat | awk 'NR==4 {print 100-$13}')"

# CPU icon
icon=

# Define mouse controls
case $BUTTON in
	# Left-click opens a terminal instance running htop
	1) setsid -f "$TERMINAL" -e htop ;;
	# Right-click creates a notification with cpu usage percentage
	3) notify-send "CPU usage" "$icon $usage%" ;;
esac

# Display icon and CPU usage (in percent)
echo "$icon $usage%"
