#!/bin/sh

memory="$(free -h | awk 'NR == 2 {print $3"/"$2}' | sed 's/i//g')"
icon=

#Define mouse controls
case $BUTTON in
	# Left-click opens a terminal instance showing advanced memory statistics
	1) setsid -f "$TERMINAL" -e watch free -h ;;
	# Right-click shows a notification with memory level
	3) notify-send "Memory" "$icon $memory" ;;
esac

# Output icon and memory stats
echo "$icon $memory"
