#!/bin/sh

# Dependencies: maim, xdotool

maim -i $(xdotool getactivewindow) -B ~/Photos/Screenshots/$(date +"%Y-%m-%d_%H-%M-%S").png && notify-send "Screenshot made!" "Screenshot saved at ~/Photos/Screenshots/$(date +"%Y-%m-%d_%H-%M-%S").png"
