#!/bin/sh

# __version__ = 0.2

# Dependencies: slock, dwm, systemctl

# Variables
locker="slock"						# Put your screen locker utility there. In my case it is slock.
logout="pkill dwm"					# Put a command to logout from DE/WM session here.
suspend="systemctl suspend"			# Put a command to suspend DE/WM session here.
hibernate="systemctl hibernate"		# Put a command to suspend DE/WM session here.
reboot="reboot"						# Put a command to reboot a machine here.
shutdown="shutdown now"				# Put a command to shutdown a machine here.

if [ -z $1 ]; then
	printf "System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (S) shutdown\n"
	read key
	case $key in
		l)
			$locker
			;;
		e)
			$logout
			;;
		s)
			$suspend && $locker
			;;
		h)
			$hibernate && $locker
			;;
		r)
			$reboot
			;;
		S)
			$shutdown
			;;
		*)
			exit 1
			;;
	esac
elif [ $1 == "l" ]; then
	$locker
elif [ $1 == "e" ]; then
	$logout
elif [ $1 == "s" ]; then
	$suspend && $locker
elif [ $1 == "h" ]; then
	$hibernate && $locker
elif [ $1 == "r" ]; then
	$reboot
elif [ $1 == "S" ]; then
	$shutdown
fi
