#!/bin/sh

# Dependencies: xclip

xclip -selection clipboard -t image/png -o > ~/Pictures/Screenshots/$(date +"%Y-%m-%d_%H-%M-%S").png && notify-send "Screenshot made!" "Screenshot saved at ~/Pictures/Screenshots/$(date +"%Y-%m-%d_%H-%M-%S").png"
